### PR TITLE
Fold example

### PR DESCRIPTION
**Pull request by jserranohidalgo**
@jeslg Just a little example `difference_1`, with, presumably, the same semantics as `difference`.

### CODE REVIEW

**Comment by jserranohidalgo** [comment]
BTW, this is my sublime configuration:

// Set to true to removing trailing white space on save
    "trim_trailing_white_space_on_save": true,

Is it yours different?

**Comment by neutropolis** [comment]
I had that option activated in atom, but I changed to vim recently. I'll find for a solution to include that feature with this editor.

**Comment by neutropolis** [comment]
I've included the new query as part of the sql tests. Currently, it's failing, since the table unification mechanism is very naive. I'll provide a fix for that as soon as possible.

**Comment by neutropolis** [comment]
Done! Your query is already working fine.

**Pull request merged**
